"""add owner_telegram_id

Revision ID: 460c511b1b33
Revises: 2b7b18475f68
Create Date: 2026-08-25 22:58:29.183869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '460c511b1b33'
down_revision: Union[str, None] = '2b7b18475f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('owner_telegram_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'owner_telegram_id')
    # ### end Alembic commands ###
