"""add channels model and update dialogs for multi-channel support

Revision ID: e878c1a2e61b
Revises: 460c511b1b33
Create Date: 2026-08-31 18:07:00.556124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e878c1a2e61b'
down_revision: Union[str, None] = '460c511b1b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('telegram', 'instagram', 'whatsapp', 'web', name='channel_type_enum'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_workspace_id'), 'channels', ['workspace_id'], unique=False)
    op.add_column('dialogs', sa.Column('channel_id', sa.Uuid(), nullable=False))
    op.add_column('dialogs', sa.Column('external_customer_id', sa.String(length=255), nullable=False))
    op.drop_index('ix_dialogs_workspace_customer', table_name='dialogs')
    op.create_index('ix_dialogs_channel_customer', 'dialogs', ['channel_id', 'external_customer_id'], unique=False)
    op.create_index(op.f('ix_dialogs_channel_id'), 'dialogs', ['channel_id'], unique=False)
    op.create_foreign_key(None, 'dialogs', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.drop_column('dialogs', 'customer_telegram_id')
    op.drop_column('workspaces', 'telegram_bot_username')
    op.drop_column('workspaces', 'owner_telegram_id')
    op.drop_column('workspaces', 'telegram_bot_token')
    op.drop_column('workspaces', 'is_bot_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('is_bot_active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('workspaces', sa.Column('telegram_bot_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('workspaces', sa.Column('owner_telegram_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('workspaces', sa.Column('telegram_bot_username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('dialogs', sa.Column('customer_telegram_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'dialogs', type_='foreignkey')
    op.drop_index(op.f('ix_dialogs_channel_id'), table_name='dialogs')
    op.drop_index('ix_dialogs_channel_customer', table_name='dialogs')
    op.create_index('ix_dialogs_workspace_customer', 'dialogs', ['workspace_id', 'customer_telegram_id'], unique=False)
    op.drop_column('dialogs', 'external_customer_id')
    op.drop_column('dialogs', 'channel_id')
    op.drop_index(op.f('ix_channels_workspace_id'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
