"""add owner telegram

Revision ID: fb8b45a40c9a
Revises: b6d80bbcfefb
Create Date: 2026-09-01 00:11:38.687594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb8b45a40c9a'
down_revision: Union[str, None] = 'b6d80bbcfefb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('owner_telegram_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'owner_telegram_id')
    # ### end Alembic commands ###
